Added mocks for Raid and Raider
MockBukkit/MockBukkit pull request #1068
Opened 2024-08-13 22:08 UTC by 4everTheOne

# Description
Implemented mocks for [Raid](https://jd.papermc.io/paper/1.20.4/org/bukkit/Raid.html) and [Raider](https://jd.papermc.io/paper/1.20.4/org/bukkit/entity/Raider.html). Raider is a abstract that will be extended by [Evoker](https://jd.papermc.io/paper/1.20.4/org/bukkit/entity/Evoker.html), [Illager](https://jd.papermc.io/paper/1.20.4/org/bukkit/entity/Illager.html), [Illusioner](https://jd.papermc.io/paper/1.20.4/org/bukkit/entity/Illusioner.html), [Pillager](https://jd.papermc.io/paper/1.20.4/org/bukkit/entity/Pillager.html), [Ravager](https://jd.papermc.io/paper/1.20.4/org/bukkit/entity/Ravager.html), [Spellcaster](https://jd.papermc.io/paper/1.20.4/org/bukkit/entity/Spellcaster.html), [Vindicator](https://jd.papermc.io/paper/1.20.4/org/bukkit/entity/Vindicator.html) and [Witch](https://jd.papermc.io/paper/1.20.4/org/bukkit/entity/Witch.html).

# Checklist
The following items should be checked before the pull request can be merged.
- [X] Code follows existing style.
- [X] Unit tests added (if applicable).

# Relates
- https://github.com/MockBukkit/MockBukkit/issues/825

2024-08-14 09:40 UTC, Thorinwasher requested changes
A small nitpick. With description I just mean writing small information about input and output for each method.

2024-08-14 09:40 UTC, Thorinwasher commented on src/main/java/be/seeseemelk/mockbukkit/RaidMock.java
> +	public void setStarted(boolean started)
As this method does not override anything, could you add a description to it?

2024-08-14 09:40 UTC, Thorinwasher commented on src/main/java/be/seeseemelk/mockbukkit/RaidMock.java
> +	public void setActiveTicks(long activeTicks)
Description here as well

2024-08-14 09:40 UTC, Thorinwasher commented on src/main/java/be/seeseemelk/mockbukkit/RaidMock.java
> +	public void setStatus(RaidStatus status)
And here

2024-08-14 09:40 UTC, Thorinwasher commented on src/main/java/be/seeseemelk/mockbukkit/RaidMock.java
> +	public void setGroupCount(int groupCount)
Here

2024-08-14 09:40 UTC, Thorinwasher commented on src/main/java/be/seeseemelk/mockbukkit/RaidMock.java
> +	public void setGroupCount(Difficulty difficulty)
Here

2024-08-14 10:35 UTC, 4everTheOne commented
Thank you for your review and i agree with it. I'll update this later in the day.

2024-08-15 06:41 UTC, Thorinwasher approved these changes
Looks good to me

2024-08-15 06:42 UTC, merged