Merge MetaMiner into the MockBukkit repository
MockBukkit/MockBukkit pull request #1069
Opened 2024-08-14 09:15 UTC by Thorinwasher

# Description
As time goes on with mocknbukkit, more generated files have been necessary to produce. From the constant updating of the generator of these files `MetaMiner` I have realised that it becomes a hassle to keep the two projects synhronized. That's why I think it's a better idea to completely merge these projects into one repository.

This pull request does exactly that, MetaMiner has now been moved into the `extra/MetaMiner` folder.

# Checklist
The following items should be checked before the pull request can be merged.
- [x] Code follows existing style.
- [n/a] Unit tests added (if applicable).

2024-08-30 10:24 UTC, Thorinwasher commented
Just going to comment, that it's probably a good idea to merge the changes from metaminer before merging this into the main branch

2024-09-15 18:40 UTC, thelooter requested changes
Please convert it to a submodule

2024-09-27 07:01 UTC, Thorinwasher commented
> Please convert it to a git submodule

I dissagree with that, with the stated reasons in my description, i.e. we need to keep these projects completely synched, Anyhow, I think this might be a somewhat heated topic, so we probably need to have a voice call about this.

2025-01-19 15:26 UTC, thelooter approved these changes

2025-01-19 15:26 UTC, merged