Implemented entity FallingBlockMock
MockBukkit/MockBukkit pull request #1083
Opened 2024-08-21 21:30 UTC by 4everTheOne

# Description
Implemented mocks for [Falling Block](https://jd.papermc.io/paper/1.21.1/org/bukkit/entity/FallingBlock.html).

# Checklist
The following items should be checked before the pull request can be merged.
- [X] Code follows existing style.
- [X] Unit tests added (if applicable).

# Relates
- https://github.com/MockBukkit/MockBukkit/issues/825

2024-08-21 21:42 UTC, thelooter commented
Is there a reason this doesn't contain World spawning logic?

2024-08-21 22:23 UTC, 4everTheOne commented
> Is there a reason this doesn't contain World spawning logic?

I forgot to add that before opening the PR. That was the reason to converting it into a draft.
Now it's ready for review :)

2024-08-22 05:09 UTC, Thorinwasher requested changes

2024-08-22 05:09 UTC, Thorinwasher commented on src/main/java/be/seeseemelk/mockbukkit/entity/FallingBlockMock.java
> +		getBlockState().setBlockData(blockData);
Here's a scenario that would cause weird behavior with this implementation:
- The blockstate is an instance of BarrelMock
- You set the blockdata to, for say to something that is not a BarrelMock related material

After doing this, the blockstate would still be an BarrelMock, and it would now have the wrong type of block data.

~~From looking at the paper implementation, it looks like they are storing the mojang equavelent of BlockData in the falling block.~~

2024-08-22 05:09 UTC, Thorinwasher commented on src/main/java/be/seeseemelk/mockbukkit/entity/FallingBlockMock.java
BlockData and BlockState are both mutable. For every getter / setter related to those you need to copy them, so as to not mutate the behavior of FallingBlockMock, whenever one of those classes get's mutated, i.e. this should not be an behavior:
```java
Directional blockData = (Directional) Material.OAK_WALL_SIGN.createBlockData();
fallingBlock.setBlockData(blockData);
blockData.setFacing(BlockFace.UP);
System.out.println(((Directional) fallingBlock.getBlockData()).getFacing());
```
Unwantede output:
```
UP
```
The default facing is expected as an output here

2024-08-22 22:05 UTC, 4everTheOne commented on src/main/java/be/seeseemelk/mockbukkit/entity/FallingBlockMock.java
If i'm not mistaken that's what happening here, but please let me know if i'm missing something:

I tested using this test and it succeeded:
```java
@Test
void test2() {
  Directional blockData = (Directional) Material.OAK_WALL_SIGN.createBlockData();
  fallingBlock.setBlockData(blockData);

  assertEquals(BlockFace.NORTH, ((Directional) fallingBlock.getBlockData()).getFacing());
  blockData.setFacing(BlockFace.EAST);
  assertEquals(BlockFace.NORTH, ((Directional) fallingBlock.getBlockData()).getFacing());
}
```

2024-08-22 22:07 UTC, 4everTheOne commented on src/main/java/be/seeseemelk/mockbukkit/entity/FallingBlockMock.java
I've updated the unit tests to include an assertion for this

2024-08-22 22:42 UTC, 4everTheOne commented on src/main/java/be/seeseemelk/mockbukkit/entity/FallingBlockMock.java
> +		getBlockState().setBlockData(blockData);
Can you validate if commit [bc27d7c](https://github.com/MockBukkit/MockBukkit/pull/1083/commits/bc27d7c6d433ae8d07bbf9584e1eaba157324fc1) fixes the issue?
Thanks

2024-08-23 12:00 UTC, Thorinwasher commented on src/main/java/be/seeseemelk/mockbukkit/entity/FallingBlockMock.java
> If i'm not mistaken that's what happening here, but please let me know if i'm missing something

Yep, that's right. I honestly just missed that

2024-08-23 12:01 UTC, Thorinwasher approved these changes
Looks good to me

2024-08-23 12:01 UTC, merged

2024-08-23 12:02 UTC, Thorinwasher commented on src/main/java/be/seeseemelk/mockbukkit/entity/FallingBlockMock.java
> +		getBlockState().setBlockData(blockData);
That probably fixes the issue