[House keeping] Mitigate project code smells
MockBukkit/MockBukkit pull request #1103
Opened 2024-09-01 18:38 UTC by 4everTheOne

# Description
This is a small PR that fixes some of the issues mentioned by Sonar.

# Checklist
The following items should be checked before the pull request can be merged.
- [X] Code follows existing style.
- [X] Unit tests added (if applicable).

2024-09-03 15:19 UTC, thelooter requested changes

2024-09-03 15:19 UTC, thelooter commented on src/main/java/be/seeseemelk/mockbukkit/adventure/Languages.java
> +	}
Please add a Test ensuring this constructor is private. Examples can be found in the codebase

2024-09-10 21:41 UTC, 4everTheOne commented on src/main/java/be/seeseemelk/mockbukkit/adventure/Languages.java
> +	}
Test has been added

2024-09-15 18:41 UTC, thelooter approved these changes

2024-09-15 18:42 UTC, merged