Life cycle event manager implementation
MockBukkit/MockBukkit pull request #1106
Opened 2024-09-02 07:54 UTC by Thorinwasher

# Description
Fixes #1064

One note currently is that I don't know exactly how to test this implementation, this pr is therefore a draft at the moment.

# Checklist
The following items should be checked before the pull request can be merged.
- [x] Code follows existing style.
- [ ] Unit tests added (if applicable).

2024-10-11 08:42 UTC, Thorinwasher commented
I just realized how nested the lifecycle event stuff is. I will put this pr on hold until I become smart enough to figure this out

2024-11-30 05:56 UTC, EnriqueGambra commented
Any updates on this PR? I would love to see this get merged in eventually :)

2024-11-30 09:11 UTC, Thorinwasher commented
> Any updates on this PR? I would love to see this get merged in eventually :)

The logic for life cycle event stuff is just so nested. It will probably take a while until I get back to this, I honestly can't find the full implementation

2025-01-20 13:25 UTC, CronixZero commented
It probably isn't possible to implement this for at least the command registration, right? Currently, Paper Plugins using this functionality aren't able to be tested

2025-01-20 13:51 UTC, Thorinwasher commented
> It probably isn't possible to implement this for at least the command registration, right?

Implementing lifecycle event command registration is/was the main purpose of this pull request. That's where I kind of gave up on it with the specified reason. I will go back and take a look on it sooner or later.

2025-05-19 18:04 UTC, 4everTheOne requested changes
Additionally to the previous comments, can you please take a look at the issues reported by sonar with severity Blocker and High? Thank you 🙂

2025-05-19 18:04 UTC, 4everTheOne commented on src/main/java/org/mockbukkit/mockbukkit/command/brigadier/DummyCommandSender.java
> +{
Can you include a comment in the empty methods please?

2025-05-19 18:04 UTC, 4everTheOne commented on src/main/java/org/mockbukkit/mockbukkit/command/brigadier/bukkit/BukkitBrigadierForwardingMapMock.java
> +public class BukkitBrigadierForwardingMapMock extends HashMap<String, Command>
Should we extend the HashMap? Can't we use more generic type like AbstractMap or Map interface?

2025-05-19 18:04 UTC, 4everTheOne commented on src/main/java/org/mockbukkit/mockbukkit/exception/PaperTagListenerManagerMock.java
Is this file needed? Looks like it's empty

2025-05-19 18:04 UTC, 4everTheOne commented on src/main/java/org/mockbukkit/mockbukkit/plugin/PluginMock.java
> -		public Builder withOnLoad(@NotNull Runnable onLoad)
This change will break the retro compatibility, due to method signature change. Should we keep a copy from the old function signature (marked as deprecated) and redirect to the new method?

2025-05-20 11:03 UTC, Thorinwasher commented on src/main/java/org/mockbukkit/mockbukkit/command/brigadier/bukkit/BukkitBrigadierForwardingMapMock.java
> +public class BukkitBrigadierForwardingMapMock extends HashMap<String, Command>
Seems like the only methods that needs to be implemented from hashmap is the equals method and to string method. Should we switch?

2025-05-22 21:57 UTC, 4everTheOne commented on src/main/java/org/mockbukkit/mockbukkit/command/brigadier/bukkit/BukkitBrigadierForwardingMapMock.java
> +public class BukkitBrigadierForwardingMapMock extends HashMap<String, Command>
I think so :)

2025-05-22 22:05 UTC, 4everTheOne reviewed
Sorry for the delay in the response.
Seems good to me! Just looks like we have a unit test failing

2025-05-23 06:58 UTC, Thorinwasher commented
> Sorry for the delay in the response. Seems good to me! Just looks like we have a unit test failing

No problem there, we all have other missions in life as well 😛. Seems like the test were failing because of an API behavior change. I also changed bukkit brigadier forwarding map to now inherit from AbstractMap

2025-05-23 07:09 UTC, Thorinwasher commented
Another note is that I have tested this locally on a plugin for the command system, it seems to function properly. But that got me thinking, this command executor that is currently used follows the behavior of a paper server, i.e. when a command fails, it sends the exception message only to the command executor if it is an instance of a brigadier exception (that I've forgotten the name of).

There should actually be some usecases with implementing our own command executor, that forwards the exception to the test, where you can simply do simple tests like this:
```java
registerCommand();
assertThrows(MyBrigadierCommandExceptin.class, () -> executor.performCommand("invalid command"));
assertDoesNotThrow(() -> executor.performCommand("valid command"));
```

2025-05-23 07:47 UTC, 4everTheOne approved these changes

2025-05-23 07:48 UTC, merged