chore(update): Update to 1.21.3
MockBukkit/MockBukkit pull request #1199
Opened 2024-11-12 19:46 UTC by thelooter

# Description
This pull request includes various updates and improvements to the MockBukkit project, including version updates, new mock classes, and enhancements to existing classes. The most important changes are as follows:

### Version Update:
* Updated `paper.api.full-version` to `1.21.3-R0.1-SNAPSHOT` in `gradle.properties`.

### New Mock Classes:
* Added `ArtMock` class to mock the `Art` interface.
* Added `AttributeMock` class to mock the `Attribute` interface.
* Added `BiomeMock` class to mock the `Biome` interface.
* Added `LockableTileStateMock` class to mock the `LockableTileState` interface.

### Enhancements to Existing Classes:
* Added `pauseWhenEmptyTime` property and related methods in `ServerMock`.
* Updated `BeaconStateMock` and `ContainerStateMock` to extend `LockableTileStateMock` instead of `TileStateMock`. 
* Updated `BoatMock` and `ChestBoatMock` to return `EntityType.OAK_BOAT` and `EntityType.OAK_CHEST_BOAT` respectively.
* Added methods to handle cooldowns in `PlayerMock`.

### Attribute Updates:
* Replaced `GENERIC_*` attributes with their updated names in `AttributesMock`, `LivingEntityMock`, and `PlayerMock`. 

# Checklist
The following items should be checked before the pull request can be merged.
- [ ] Code follows existing style.
- [ ] Unit tests added (if applicable).

2024-11-13 00:05 UTC, 4everTheOne reviewed
Looks good to me, just have some tiny details

2024-11-13 00:05 UTC, 4everTheOne commented on src/main/java/org/mockbukkit/mockbukkit/ServerMock.java
> +	private int pauseWhenEmptyTime =60 ;
sorry for the preciousness
```suggestion
	private int pauseWhenEmptyTime = 60;
```

2024-11-13 00:05 UTC, 4everTheOne commented on src/main/java/org/mockbukkit/mockbukkit/entity/PlayerMock.java
> +
Should we throw a `UnimplementedOperationException` or implement it?

2024-11-13 00:05 UTC, 4everTheOne commented on src/main/java/org/mockbukkit/mockbukkit/util/UnsafeValuesMock.java
> +			customBiome = new BiomeMock(NamespacedKey.fromString("mockbukkit:custom"));
Should we move this logic and encapsulate it inside a method `BiomeMock.createCustom()`? It may be useful for other tests

2024-11-13 16:22 UTC, Thorinwasher requested changes
Mostly nitpicks, about parameters for unimplemented methods, this might in hindsight not matter that much.

2024-11-13 16:22 UTC, Thorinwasher commented on src/main/java/org/mockbukkit/mockbukkit/ServerMock.java
> +	public void setPauseWhenEmptyTime(int i)
Change this to a proper parameter name

2024-11-13 16:22 UTC, Thorinwasher commented on src/main/java/org/mockbukkit/mockbukkit/block/state/LockableTileStateMock.java
> +	public abstract void setLock(@Nullable String s);
Parameter name

2024-11-13 16:22 UTC, Thorinwasher commented on src/main/java/org/mockbukkit/mockbukkit/entity/CommandMinecartMock.java
> +import net.kyori.adventure.util.TriState;
Unnecessary import (nitpick)

2024-11-13 16:22 UTC, Thorinwasher commented on src/main/java/org/mockbukkit/mockbukkit/entity/ExplosiveMinecartMock.java
> +	public void setYield(float v)
Parameter name

2024-11-13 16:22 UTC, Thorinwasher commented on src/main/java/org/mockbukkit/mockbukkit/entity/ExplosiveMinecartMock.java
> +	public void setIsIncendiary(boolean b)
Parameter name

2024-11-13 16:22 UTC, Thorinwasher commented on src/main/java/org/mockbukkit/mockbukkit/entity/LivingEntityMock.java
> +import org.w3c.dom.Attr;
Might have missed this, but this import is probably not necessary (another nitpick)

2024-11-13 16:22 UTC, Thorinwasher commented on src/main/java/org/mockbukkit/mockbukkit/entity/PlayerMock.java
> +		return false;
Implementation of non parity behavior, if possible throw an unimplemented operation exception here

2024-11-13 16:22 UTC, Thorinwasher commented on src/main/java/org/mockbukkit/mockbukkit/entity/PlayerMock.java
> +		return 0;
Same here, non parity behavior

2024-11-13 16:22 UTC, Thorinwasher commented on src/main/java/org/mockbukkit/mockbukkit/entity/PlayerMock.java
> +	public void setCooldown(@NotNull ItemStack itemStack, int i)
Parameter name

2024-11-13 16:22 UTC, Thorinwasher commented on src/main/java/org/mockbukkit/mockbukkit/entity/PlayerMock.java
> +	public void setPlayerListOrder(int i)
parameter names

2024-11-13 16:22 UTC, Thorinwasher commented on src/main/java/org/mockbukkit/mockbukkit/sound/MusicInstrumentMock.java
> +		throw new UnimplementedOperationException();
I remember adding translation keys automatically to all json files, should be able to fetch this using MetaMiner if I'm not wrong of course

2024-11-13 16:25 UTC, Thorinwasher commented on src/main/java/org/mockbukkit/mockbukkit/ServerMock.java
> +	private int pauseWhenEmptyTime =60 ;
```suggestion
	private int pauseWhenEmptyTime = 60;
```

2024-11-13 16:27 UTC, Thorinwasher commented on src/main/java/org/mockbukkit/mockbukkit/entity/PlayerMock.java
> +
either of those alternatives is fine, I'm leaning towards UnimplementedOperationException, if no tests are failing from that

2024-12-03 15:17 UTC, ens-gijs commented on src/main/java/org/mockbukkit/mockbukkit/world/WorldMock.java
> +	public void getChunkAtAsync(int i, int i1, boolean b, boolean b1, @NotNull Consumer<? super Chunk> consumer)
parameter naming

2024-12-03 15:17 UTC, ens-gijs commented on src/main/java/org/mockbukkit/mockbukkit/world/WorldMock.java
> +	public void getChunksAtAsync(int i, int i1, int i2, int i3, boolean b, @NotNull Runnable runnable)
parameter naming

2024-12-13 22:26 UTC, 4everTheOne approved these changes

2024-12-15 19:46 UTC, Thorinwasher approved these changes
Looked shortly through this, all the points I addressed have been fixed.

2024-12-15 21:45 UTC, merged