Change coverage workflow name and remove unnecessary coverage run
MockBukkit/MockBukkit pull request #1206
Opened 2024-11-19 17:53 UTC by Thorinwasher

# Description

# Checklist
The following items should be checked before the pull request can be merged.
- [ ] Code follows existing style.
- [ ] Unit tests added (if applicable).

2024-11-19 17:55 UTC, thelooter requested changes

2024-11-19 17:55 UTC, thelooter commented on .github/workflows/coverage.yaml
> -    branches: [ v1.*]
This will make it not run on v1.21 , which is required for codecov to actually display our current coverage and coverage over time

2024-11-19 19:10 UTC, 4everTheOne commented
What do you think about renaming this action to:
> Coverage / check

2024-11-19 19:15 UTC, Thorinwasher commented
> What do you think about renaming this action to:
> 
> > Coverage / check

Like this?
![image](https://github.com/user-attachments/assets/582fda52-488f-47c6-a1de-54b1fa8deaf3)

2024-11-20 00:46 UTC, 4everTheOne commented
I was thinking more like this:
![image](https://github.com/user-attachments/assets/c113f5a9-6a92-4228-8e3f-21f5f75e75fb)

2024-11-20 07:53 UTC, Thorinwasher commented
> I was thinking more like this: ![image](https://private-user-images.githubusercontent.com/5434488/387885198-c113f5a9-6a92-4228-8e3f-21f5f75e75fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwODkyNjIsIm5iZiI6MTczMjA4ODk2MiwicGF0aCI6Ii81NDM0NDg4LzM4Nzg4NTE5OC1jMTEzZjVhOS02YTkyLTQyMjgtOGUzZi0yMWY1Zjc1ZTc1ZmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjBUMDc0OTIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTRiY2FlYjI3NTJmZGEzYjAzNGVmYjYxODBjYTVlZWQ2OTM2MmE2OGMzMjdiMzJmY2RlYzM1ZDYzNmI1MjFkMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.SU32g8uABVXsIutcF4myfQkCSsf6OSuW5YikTEb1H2s)

I think that would mean renaming the workflow file from `coverage.yml` to `check.yml`. I think it's better to have a more descriptive file name, such as `coverage.yml`.

2024-11-22 20:46 UTC, 4everTheOne approved these changes

2025-05-16 13:37 UTC, merged