Implement Player block place
MockBukkit/MockBukkit pull request #140
Opened 2020-12-02 15:38 UTC by JacksonChen666

# Description
This is a basic implementation of player block placing, and resolves #111.

# Checklist
The following items should be checked before the pull request can be merged.
- [x] Version number updated in `settings.gradle`.
- [x] Unit tests added.
- [x] Code follows existing code format.

# Info on creating a pull request
Before the pull request can be accepted, the version number stored in settings.gradle should be updated.
MockBukkit uses semantic-versioning (https://semver.org/)

 - If the PR fixes a bug in MockBukkit, update the patch version. (if the current version is `0.4.1`, the new version should be `0.4.2`)
 - If the PR adds a new feature to MockBukkit, update minor version. (if the current version is `0.4.1`, the new version should be `0.5.0`)
 - Make sure that unit tests are added which test the relevant changes.
 - Make sure that the changes follow the existing code format.

Note that a PR that fixes an `UnimplementedOperationException` should be considered a new version and not a bugfix.

The version number can be found in `settings.gradle`.

2020-12-12 18:25 UTC, seeseemelk requested changes

2020-12-12 18:25 UTC, seeseemelk commented on src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
> +		if ((gamemode == GameMode.ADVENTURE || gamemode == GameMode.SPECTATOR))
Why are there two parenthesis here?

2020-12-12 18:25 UTC, seeseemelk commented on src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
> +	 * @param location The location of the material to set to
Missing documentation for the return type. It returns a bool, but what does the bool mean exactly? Is it `true` if the block was placed and `false` if it was not placed?

2020-12-17 13:05 UTC, JacksonChen666 commented
Currently waiting for re-review as changes that were requested has been completed.

2020-12-28 11:02 UTC, seeseemelk approved these changes

2020-12-28 11:02 UTC, merged