Implement HelpMap
MockBukkit/MockBukkit pull request #142
Opened 2020-12-06 22:16 UTC by NeumimTo

# Description
Implementation of HelpMap

# Checklist
The following items should be checked before the pull request can be merged.
- [ ] Version number updated in `settings.gradle`.
- [ ] Unit tests added.
- [ ] Code follows existing code format.

2020-12-08 00:08 UTC, TheBusyBiscuit requested changes
There is one thing that should definitely be addressed.
Other than that this is looking pretty good!

*Can't really say much about it, I haven't ever used the HelpMap before actually*

2020-12-08 00:08 UTC, TheBusyBiscuit commented on src/main/java/be/seeseemelk/mockbukkit/help/HelpMapMock.java
> +import java.util.*;
Please do not use wildcard imports, there is absolutely no need to import the entire java.util library.
It serves no benefit here other than polluting this namespace.

2020-12-08 19:02 UTC, NeumimTo commented
> There is one thing that should definitely be addressed.
> Other than that this is looking pretty good!
> 
> _Can't really say much about it, I haven't ever used the HelpMap before actually_

Me neither, but i need to test a plugin that relies on ACF, which requires it under the hood somehow.

2020-12-12 18:28 UTC, seeseemelk approved these changes

2020-12-12 18:28 UTC, merged