Change simulate methods in PlayerMock to return the event they fired. Change build.gradle to run tests.
MockBukkit/MockBukkit pull request #219
Opened 2021-06-01 15:13 UTC by carelesshippo

# Description
State the changes of the pull request here.
This pull request changed the simulate methods in `PlayerMock` to return the event that they fired to allow for better testing. This pull request also added the lines:
```
test {
    useJUnitPlatform()
}
```
to the build.gradle file so that the junit tests run when the test task is run. If this was intentional, let me know so that I can roll back the file.

# Checklist
The following items should be checked before the pull request can be merged.
- [x] Version number updated in `settings.gradle`.
- [x] Unit tests added.
- [x] Code follows existing code format.

# Info on creating a pull request
Before the pull request can be accepted, the version number stored in settings.gradle should be updated.
MockBukkit uses semantic-versioning (https://semver.org/)

 - If the PR fixes a bug in MockBukkit, update the patch version. (if the current version is `0.4.1`, the new version should be `0.4.2`)
 - If the PR adds a new feature to MockBukkit, update minor version. (if the current version is `0.4.1`, the new version should be `0.5.0`)
 - Make sure that unit tests are added which test the relevant changes.
 - Make sure that the changes follow the existing code format.

Note that a PR that fixes an `UnimplementedOperationException` should be considered a new version and not a bugfix.

The version number can be found in `settings.gradle`.

2021-06-01 17:24 UTC, TheBusyBiscuit requested changes
Looks good to me, some missing annotations can be added though

2021-06-01 17:24 UTC, TheBusyBiscuit commented on src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
> +	public PlayerMoveEvent simulatePlayerMove(@NotNull Location moveLocation)
```suggestion
	public @NotNull PlayerMoveEvent simulatePlayerMove(@NotNull Location moveLocation)
```

2021-06-01 17:24 UTC, TheBusyBiscuit commented on src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
> +	public PlayerToggleSneakEvent simulateSneak(boolean sneak)
```suggestion
	public @NotNull PlayerToggleSneakEvent simulateSneak(boolean sneak)
```

2021-06-01 17:24 UTC, TheBusyBiscuit commented on src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
> +	public PlayerToggleSprintEvent simulateSprint(boolean sprint)
```suggestion
	public @NotNull PlayerToggleSprintEvent simulateSprint(boolean sprint)
```

2021-06-01 17:24 UTC, TheBusyBiscuit commented on src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
> +	public PlayerToggleFlightEvent simulateToggleFlight(boolean fly)
```suggestion
	public @NotNull PlayerToggleFlightEvent simulateToggleFlight(boolean fly)
```

2021-06-01 17:24 UTC, TheBusyBiscuit commented on build.gradle
> +    useJUnitPlatform()
Afaik the `Junit` *should* be the default, so this shouldn't be necessary.
But it cannot hurt to declare this explicitly. 👍🏻

2021-06-02 01:18 UTC, carelesshippo commented
Those requests should be implemented now. As for Junit, it must have been a local preference that made it so tests didn't run for some reason.

2021-06-02 16:06 UTC, TheBusyBiscuit approved these changes
LGTM.

Thanks for changing that one unit test to a ParameterizedTest and fixing that typo!

2021-06-02 16:07 UTC, merged

2021-06-03 07:58 UTC, seeseemelk commented
I'm a little bit considered that the return values of the simulate methods were changed. This introduces a breaking change which could break projects when they attempt to upgrade from `v1.1.0` to `v1.2.0`. I would have preferred to see these being introduced under a slightly different name, and have the old methods be annotated with `@deprecated`. But it has already been merged

2021-06-03 10:35 UTC, TheBusyBiscuit commented
@seeseemelk Oh, sorry about that.
We can always change that in retrospect, afaik you haven't pushed it to maven-central yet right?