Fix PlayerTeleportEvent not firing when player is teleported.
MockBukkit/MockBukkit pull request #224
Opened 2021-06-03 23:02 UTC by carelesshippo

# Description
State the changes of the pull request here.
Fixes the player teleport event not firing when a player is teleported

# Checklist
The following items should be checked before the pull request can be merged.
- [x] Version number updated in `settings.gradle`.
- [x] Unit tests added.
- [x] Code follows existing code format.

# Info on creating a pull request
Before the pull request can be accepted, the version number stored in settings.gradle should be updated.
MockBukkit uses semantic-versioning (https://semver.org/)

 - If the PR fixes a bug in MockBukkit, update the patch version. (if the current version is `0.4.1`, the new version should be `0.4.2`)
 - If the PR adds a new feature to MockBukkit, update minor version. (if the current version is `0.4.1`, the new version should be `0.5.0`)
 - Make sure that unit tests are added which test the relevant changes.
 - Make sure that the changes follow the existing code format.

Note that a PR that fixes an `UnimplementedOperationException` should be considered a new version and not a bugfix.

The version number can be found in `settings.gradle`.

2021-06-03 23:04 UTC, TheBusyBiscuit requested changes

2021-06-03 23:04 UTC, TheBusyBiscuit commented on src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
> +	public boolean teleport(@NotNull Location location, PlayerTeleportEvent.@NotNull TeleportCause cause)
```suggestion
	public boolean teleport(@NotNull Location location, @NotNull PlayerTeleportEvent.TeleportCause cause)
```

2021-06-06 10:08 UTC, TheBusyBiscuit approved these changes
Looks good to me thus far.
Bukkit does quite a few more things on teleporting though, such as closing the inventory, preventing the teleportation of dead players etc..
But I doubt these will be relevant in this simplified environment, so it should be good for now. Perhaps Seeseemelk wants to have a look at it before-hand though, so I'll wait on merging it until he had a look at it. But it is an approval from me.

2021-06-19 12:58 UTC, seeseemelk approved these changes
Looks pretty good. The only thing to change is perhaps the version number. It was bumped from 1.2.0 to 1.2.1, but it's not a bug fix so it should have been 1.3.0. I've gone ahead a fixed that though.

2021-06-19 12:58 UTC, merged