Add statistics implementation
MockBukkit/MockBukkit pull request #231
Opened 2021-06-24 02:59 UTC by okx-code

# Description
Add implementation for `Player#setStatistic`, `Player#getStatistic` etc

# Checklist
The following items should be checked before the pull request can be merged.
- [x] Version number updated in `settings.gradle`.
- [x] Unit tests added.
- [x] Code follows existing code format.

2021-06-24 10:08 UTC, TheBusyBiscuit requested changes

2021-06-24 10:08 UTC, TheBusyBiscuit commented on src/main/java/be/seeseemelk/mockbukkit/statistic/StatisticMock.java
> +	private final Map<Statistic, Map<EntityType, Integer>> entityStatistics = new HashMap<>();
`Statistic` is an enum, so these should all be `EnumMap`s.

2021-06-24 10:08 UTC, TheBusyBiscuit commented on src/main/java/be/seeseemelk/mockbukkit/statistic/StatisticMock.java
> +	}
Some `@NotNull` annotations for parameters would be nice.

2021-06-24 10:08 UTC, TheBusyBiscuit commented on src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
> +		statistics.setStatistic(statistic, statistics.getStatistic(statistic) - amount);
two operations for what can be done in one, I suggest you to add a `increment` and `decrement` method in your `StatisticsMock` and implement the logic there.

2021-06-24 10:08 UTC, TheBusyBiscuit commented on src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
> +		statistics.setStatistic(statistic, material, statistics.getStatistic(statistic, material) - amount);
two operations for what can be done in one, I suggest you to add a `increment` and `decrement` method in your `StatisticsMock` and implement the logic there.

2021-06-24 10:08 UTC, TheBusyBiscuit commented on src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java
> +		statistics.setStatistic(statistic, entityType, statistics.getStatistic(statistic, entityType) - amount);
two operations for what can be done in one, I suggest you to add a `increment` and `decrement` method in your `StatisticsMock` and implement the logic there.

2021-06-24 10:08 UTC, TheBusyBiscuit commented on src/main/java/be/seeseemelk/mockbukkit/statistic/StatisticMock.java
> +public class StatisticMock
Some javadocs would be nice :eyes:

For the class and methods

2021-06-24 10:08 UTC, TheBusyBiscuit commented on src/main/java/be/seeseemelk/mockbukkit/statistic/StatisticMock.java
> +public class StatisticMock
Also shouldn't this be `StatisticsMock` (plural, since it holds multiple).

2021-06-24 14:11 UTC, okx-code commented
I've added your suggested improvements.

2021-06-25 16:57 UTC, TheBusyBiscuit approved these changes
There is still a bit room for optimization left but it looks good to me

2021-06-25 16:57 UTC, merged