Implementation of getViewers() and remove. Tests too
MockBukkit/MockBukkit pull request #234
Opened 2021-07-10 19:51 UTC by TechnicalBro

# Description
Implementation of Inventory::getViewers, and Inventory::remove

Needed it for writing unit tests on my own project 

# Checklist
The following items should be checked before the pull request can be merged.
- [ X] Version number updated in `settings.gradle`.
- [ X] Unit tests added.
- [ X] Code follows existing code format.

# Info on creating a pull request
Before the pull request can be accepted, the version number stored in settings.gradle should be updated.
MockBukkit uses semantic-versioning (https://semver.org/)

 - If the PR fixes a bug in MockBukkit, update the patch version. (if the current version is `0.4.1`, the new version should be `0.4.2`)
 - If the PR adds a new feature to MockBukkit, update minor version. (if the current version is `0.4.1`, the new version should be `0.5.0`)
 - Make sure that unit tests are added which test the relevant changes.
 - Make sure that the changes follow the existing code format.

Note that a PR that fixes an `UnimplementedOperationException` should be considered a new version and not a bugfix.

The version number can be found in `settings.gradle`.

2021-07-10 20:05 UTC, TheBusyBiscuit requested changes
I couldn't be bothered marking all the other issues in regards to formatting.
Please follow the project's code and brace style.

2021-07-10 20:05 UTC, TheBusyBiscuit commented on settings.gradle
> +gradle.ext.version = '1.5.1'
You are adding a feature, so the version should be `1.6.0`
```suggestion
gradle.ext.version = '1.6.0'
```

2021-07-10 20:05 UTC, TheBusyBiscuit commented on src/main/java/be/seeseemelk/mockbukkit/inventory/InventoryMock.java
> +import java.util.*;
Don't import the entirety of `java.util` ._.

You should try to avoid wildcard imports in general.

2021-07-10 20:05 UTC, TheBusyBiscuit commented on src/main/java/be/seeseemelk/mockbukkit/inventory/InventoryMock.java
> +import static org.junit.jupiter.api.Assertions.*;
Please avoid wildcard imports

2021-07-10 20:05 UTC, TheBusyBiscuit commented on src/main/java/be/seeseemelk/mockbukkit/inventory/InventoryMock.java
> +public class InventoryMock implements Inventory {
You broke the formatting here.

```suggestion
public class InventoryMock implements Inventory
{
```

2021-07-10 20:05 UTC, TheBusyBiscuit commented on src/main/java/be/seeseemelk/mockbukkit/inventory/InventoryMock.java
> +	public InventoryMock(@Nullable InventoryHolder holder, @NotNull InventoryType type) {
You broke the formatting here.
```suggestion
	public InventoryMock(@Nullable InventoryHolder holder, @NotNull InventoryType type)
	{
```

2021-07-10 20:05 UTC, TheBusyBiscuit commented on src/main/java/be/seeseemelk/mockbukkit/inventory/InventoryMock.java
> +		for (ItemStack item : items) {
You broke the formatting here.
```suggestion
	public void assertTrueForAll(@NotNull Predicate<ItemStack> condition)
	{
		for (ItemStack item : items)
		{
```

2021-07-10 20:05 UTC, TheBusyBiscuit commented on src/main/java/be/seeseemelk/mockbukkit/inventory/InventoryMock.java
> +	public void assertTrueForNonNulls(@NotNull Predicate<ItemStack> condition) {
You broke the formatting here.
```suggestion
	public void assertTrueForNonNulls(@NotNull Predicate<ItemStack> condition)
	{
```

2021-07-10 20:05 UTC, TheBusyBiscuit commented on src/main/java/be/seeseemelk/mockbukkit/inventory/InventoryMock.java
> +			if (item != null && condition.test(item)) {
You broke the formatting here.

```suggestion
	public void assertTrueForSome(@NotNull Predicate<ItemStack> condition)
	{
		for (ItemStack item : items)
		{
			if (item != null && condition.test(item))
			{
```

2021-07-10 20:05 UTC, TheBusyBiscuit commented on src/main/java/be/seeseemelk/mockbukkit/inventory/InventoryMock.java
> +	public void assertContainsAny(@NotNull ItemStack item) {
You broke the formatting here.

```suggestion
	public void assertContainsAny(@NotNull ItemStack item)
	{
```

2021-07-10 20:05 UTC, TheBusyBiscuit commented on src/main/java/be/seeseemelk/mockbukkit/inventory/InventoryMock.java
> +	public void assertContainsAtLeast(@NotNull ItemStack item, int amount) {
You broke the formatting here.

```suggestion
	public void assertContainsAtLeast(@NotNull ItemStack item, int amount)
	{
```

2021-07-10 20:05 UTC, TheBusyBiscuit commented on src/main/java/be/seeseemelk/mockbukkit/inventory/InventoryMock.java
> +	public int getNumberOfItems(@NotNull ItemStack item) {
You broke the formatting here.
```suggestion
	public int getNumberOfItems(@NotNull ItemStack item)
	{
```

2021-07-10 20:05 UTC, TheBusyBiscuit commented on src/main/java/be/seeseemelk/mockbukkit/inventory/InventoryMock.java
> +			if (itemstack != null && item.isSimilar(itemstack)) {
You broke the formatting here.

```suggestion
		for (ItemStack itemstack : items)
		{
			if (itemstack != null && item.isSimilar(itemstack))
			{
```

2021-07-10 20:05 UTC, TheBusyBiscuit commented on src/main/java/be/seeseemelk/mockbukkit/inventory/InventoryMock.java
> +	private Map<Integer, ItemStack> contentsToMap() {
You broke the formatting here.

Also missing annotation.

```suggestion
	private @NotNull Map<Integer, ItemStack> contentsToMap()
	{
```

2021-07-10 20:05 UTC, TheBusyBiscuit commented on src/main/java/be/seeseemelk/mockbukkit/inventory/InventoryMock.java
> +	public int getSize() {
You broke the formatting here.

```suggestion
	public int getSize()
	{
```

2021-07-13 13:16 UTC, TechnicalBro commented
Alright noted.

2021-07-17 13:53 UTC, TheBusyBiscuit commented
What the...
How did you manage to break literally everything...?

This will be a hard rejection. Please fix your set up so that it doesn't break the entire project and perhaps PR again later.

2021-07-17 13:53 UTC, closed without merging