fix(player): getOfflinePlayer returns random player with different id
MockBukkit/MockBukkit pull request #278
Opened 2021-12-06 09:09 UTC by Silthus

# Description
Querying for an `OfflinePlayer` with `ServerMock.getOfflinePlayer(UUID)` returns a random offline player that has a different id. This can lead to an endless loop.

# Checklist
The following items should be checked before the pull request can be merged.
- [ ] Version number updated in `settings.gradle`.
- [X] Unit tests added.
- [X] Code follows existing code format.

2021-12-06 12:11 UTC, TheBusyBiscuit requested changes
LGTM, small change though.
And the version number needs to be updated.

2021-12-06 12:11 UTC, TheBusyBiscuit commented on src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMockFactory.java
> +	public @NotNull OfflinePlayerMock createOfflinePlayer(UUID uuid)
```suggestion
	public @NotNull OfflinePlayerMock createOfflinePlayer(@NotNull UUID uuid)
```

2021-12-06 16:42 UTC, Silthus commented
Ok thank you. I bumped the version and added the `@NotNull`.

2021-12-08 18:55 UTC, TheBusyBiscuit approved these changes
LGTM

2021-12-08 18:55 UTC, merged