Implement AI
MockBukkit/MockBukkit pull request #380
Opened 2022-05-28 22:35 UTC by thelooter

# Description
Implement AI on LivingEntityMock

# Checklist
The following items should be checked before the pull request can be merged.
- [ ] Unit tests added.
- [ ] Code follows existing code format.

# Info on creating a pull request
- Make sure that unit tests are added which test the relevant changes.
- Make sure that the changes follow the existing code format.

# For maintainer
When a PR is approved, the maintainer should label this PR with `release/*`.

- If the PR fixes a bug in MockBukkit, update the patch version. (if the current version is `0.4.1`, the new version should be `0.4.2`)
- If the PR adds a new feature to MockBukkit, update minor version. (if the current version is `0.4.1`, the new version should be `0.5.0`)

Note that a PR that fixes an `UnimplementedOperationException` should be considered a new version and not a bugfix.

2022-05-28 23:33 UTC, Insprill requested changes

2022-05-28 23:33 UTC, Insprill commented on src/test/java/be/seeseemelk/mockbukkit/entity/EntityMockTest.java
> +
There should be a test to ensure non-mob entities have no ai, and that setting it doesn't change that.

2022-05-28 23:33 UTC, Insprill commented
This is already implemented in #328. Not sure if it'd be better to merge this now or wait until then since 328 might take a while.

2022-05-29 10:33 UTC, thelooter commented
> This is already implemented in #328. Not sure if it'd be better to merge this now or wait until then since 328 might take a while.

I would probably wait till that is merged. So I will close this PR now

2022-05-29 10:33 UTC, closed without merging