Implement the End Gateway BlockState
MockBukkit/MockBukkit pull request #493
Opened 2022-06-21 23:03 UTC by Insprill

# Description
Creates an `EndGatewayMock`.

# Checklist
The following items should be checked before the pull request can be merged.
- [x] Unit tests added.
- [x] Code follows existing code format.

2022-06-29 08:27 UTC, syldium requested changes
Some nitpicks, since a location is mutable and refers to a world.

2022-06-29 08:27 UTC, syldium commented on src/main/java/be/seeseemelk/mockbukkit/block/state/EndGatewayMock.java
> +		this.exitLocation = location;
```suggestion
		Preconditions.checkArgument(location == null || Objects.equals(location.getWorld(), isPlaced() ? getWorld() : null), "Cannot set exit location to different world");
		this.exitLocation = location == null ? null : location.toBlockLocation();
```
`Location#toBlockLocation` clones the location, so the state owns this block position.

2022-06-29 08:27 UTC, syldium commented on src/main/java/be/seeseemelk/mockbukkit/block/state/EndGatewayMock.java
> +		return this.exitLocation;
```suggestion
		return this.exitLocation == null ? null : this.exitLocation.clone();
```
The location shouldn't be modifiable without using `setExitLocation`.

2022-06-29 08:27 UTC, syldium commented on src/test/java/be/seeseemelk/mockbukkit/block/state/EndGatewayMockTest.java
> +		gateway.setExitLocation(new Location(null, 4, 2, 0));
```suggestion
		gateway.setExitLocation(new Location(this.world, 4, 2, 0));
```
The exit world should be equal to `BlockState#getWorld()`.

2022-06-29 09:37 UTC, Insprill commented
> Some nitpicks, since a location is mutable and refers to a world.

Thank you! Looks like I got a bit hasty on this one and didn't do my research.

2022-07-04 22:01 UTC, thelooter approved these changes

2022-07-04 22:24 UTC, merged