Fix/async events
MockBukkit/MockBukkit pull request #532
Opened 2022-07-08 12:23 UTC by Hokkaydo

# Description
This PR adds patches applied on v1.18 branch to v1.16 branch concerning BukkitSchedulerMock and its failures about AsyncTasks' stopping

# Checklist
The following items should be checked before the pull request can be merged.
- [x] No unit tests added but updated older one
- [x] Code follows existing code format.

2022-07-08 14:09 UTC, thelooter requested changes
Just one small thing

2022-07-08 14:09 UTC, thelooter commented on src/main/java/be/seeseemelk/mockbukkit/scheduler/BukkitSchedulerMock.java
>  			throw new AsyncTaskException(asyncException.get());
```suggestion
		if (asyncException.get() != null)
		{
			throw new AsyncTaskException(asyncException.get());
        }
```

2022-07-08 14:42 UTC, thelooter approved these changes

2022-07-09 19:33 UTC, Insprill commented
Closing as this doesn't actually fix the issue. #536 should do the trick.

2022-07-09 19:33 UTC, closed without merging