Implements the Animals#isBreedingItem Methods
MockBukkit/MockBukkit pull request #533
Opened 2022-07-08 15:21 UTC by thelooter

# Description
Implements the Breeding Item Methods and override them if necessary

# Checklist
The following items should be checked before the pull request can be merged.
- [x] Unit tests added.
- [x] Code follows existing code format.

# Info on creating a pull request
- Make sure that unit tests are added which test the relevant changes.
- Make sure that the changes follow the existing code format.

# For maintainer
When a PR is approved, the maintainer should label this PR with `release/*`.

- If the PR fixes a bug in MockBukkit, update the patch version. (if the current version is `0.4.1`, the new version should be `0.4.2`)
- If the PR adds a new feature to MockBukkit, update minor version. (if the current version is `0.4.1`, the new version should be `0.5.0`)

Note that a PR that fixes an `UnimplementedOperationException` should be considered a new version and not a bugfix.

2022-07-08 17:49 UTC, Insprill requested changes

2022-07-08 17:49 UTC, Insprill commented on src/main/java/be/seeseemelk/mockbukkit/entity/AxolotlMock.java
> +	}
Can this be moved to AnimalsMock?

2022-07-08 17:49 UTC, Insprill commented on src/main/java/be/seeseemelk/mockbukkit/entity/ChickenMock.java
> +	}
Can this be moved to AnimalsMock?

2022-07-09 18:15 UTC, TheBusyBiscuit commented on src/main/java/be/seeseemelk/mockbukkit/entity/AxolotlMock.java
> +	}
This is already within `AnimalsMock`. It doesn't have to be moved, it can just be removed.

2022-07-09 18:15 UTC, TheBusyBiscuit commented on src/main/java/be/seeseemelk/mockbukkit/entity/ChickenMock.java
> +	}
This is already within `AnimalsMock`. It doesn't have to be moved, it can just be removed.

2022-07-09 18:16 UTC, thelooter commented on src/main/java/be/seeseemelk/mockbukkit/entity/AxolotlMock.java
> +	}
Yeah will do as soon as I get home

2022-07-10 08:51 UTC, TheBusyBiscuit approved these changes
LGTM

2022-07-10 08:54 UTC, Insprill approved these changes
LGTM

2022-07-10 08:55 UTC, merged