Add Missed Tests
MockBukkit/MockBukkit pull request #542
Opened 2022-07-12 22:43 UTC by thelooter

# Description
Add missed Tests

# Checklist
The following items should be checked before the pull request can be merged.
- [x] Unit tests added.
- [x] Code follows existing code format.

# Info on creating a pull request
- Make sure that unit tests are added which test the relevant changes.
- Make sure that the changes follow the existing code format.

# For maintainer
When a PR is approved, the maintainer should label this PR with `release/*`.

- If the PR fixes a bug in MockBukkit, update the patch version. (if the current version is `0.4.1`, the new version should be `0.4.2`)
- If the PR adds a new feature to MockBukkit, update minor version. (if the current version is `0.4.1`, the new version should be `0.5.0`)

Note that a PR that fixes an `UnimplementedOperationException` should be considered a new version and not a bugfix.

2022-07-12 22:46 UTC, Insprill requested changes

2022-07-12 22:46 UTC, Insprill commented on .github/workflows/gradle.yml
> +        uses: DamianReeves/write-file-action@v1.0
Was this intentional?

2022-07-12 22:46 UTC, Insprill commented on src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
> +	void testDisConnectWithPlayerOffline()
*Disconnect

2022-07-12 22:50 UTC, thelooter commented on src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
> +	void testDisConnectWithPlayerOffline()
thanks

2022-07-12 22:50 UTC, thelooter commented on .github/workflows/gradle.yml
> +        uses: DamianReeves/write-file-action@v1.0
Nope

2022-07-14 13:57 UTC, Insprill requested changes

2022-07-14 13:57 UTC, Insprill commented on src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
> +		assertFalse(server.getOnlinePlayers().contains(player));
This fails since the player is being added to the online player's list twice. perhaps a set should be used and the handling should be cleaned up.

2022-07-14 14:51 UTC, thelooter commented on src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
> +		assertFalse(server.getOnlinePlayers().contains(player));
Should I do this in this PR or should I create a Separate PR?

2022-07-14 15:04 UTC, Insprill commented on src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
> +		assertFalse(server.getOnlinePlayers().contains(player));
A separate one, please.

2022-07-21 05:18 UTC, Insprill requested changes

2022-07-21 05:18 UTC, Insprill commented on src/test/java/be/seeseemelk/mockbukkit/entity/AgeableMockTest.java
> +	AgeableMock ageable;
```suggestion
	private ServerMock serverMock;
	private AgeableMock ageable;

2022-07-21 05:18 UTC, Insprill commented on src/test/java/be/seeseemelk/mockbukkit/entity/AnimalsMockTest.java
> +
```suggestion

2022-07-21 05:18 UTC, Insprill commented on src/test/java/be/seeseemelk/mockbukkit/entity/AnimalsMockTest.java
>  }
```suggestion
	}

}

2022-07-21 05:18 UTC, Insprill commented on src/test/java/be/seeseemelk/mockbukkit/entity/ChestedHorseMockTest.java
> +}
```suggestion
	}

}
```

2022-07-22 00:54 UTC, Insprill approved these changes
LGTM

2022-07-22 01:00 UTC, merged