Add BeaconInventoryMock
MockBukkit/MockBukkit pull request #549
Opened 2022-07-14 16:53 UTC by thelooter

# Description
Adds a Mock for the BeaconInventory 

# Checklist
The following items should be checked before the pull request can be merged.
- [x] Unit tests added.
- [x] Code follows existing code format.

# Info on creating a pull request
- Make sure that unit tests are added which test the relevant changes.
- Make sure that the changes follow the existing code format.

# For maintainer
When a PR is approved, the maintainer should label this PR with `release/*`.

- If the PR fixes a bug in MockBukkit, update the patch version. (if the current version is `0.4.1`, the new version should be `0.4.2`)
- If the PR adds a new feature to MockBukkit, update minor version. (if the current version is `0.4.1`, the new version should be `0.5.0`)

Note that a PR that fixes an `UnimplementedOperationException` should be considered a new version and not a bugfix.

2022-07-14 16:56 UTC, thelooter commented
Yeah, I might have forgotten to add Tests to that class :sweat_smile:

2022-07-15 01:26 UTC, Insprill requested changes

2022-07-15 01:26 UTC, Insprill commented on src/main/java/be/seeseemelk/mockbukkit/inventory/BeaconInventoryMock.java
> +	@Nullable ItemStack item;
```suggestion
{

	private @Nullable ItemStack item;

2022-07-15 01:26 UTC, Insprill commented on src/main/java/be/seeseemelk/mockbukkit/inventory/BeaconInventoryMock.java
> +}
```suggestion
	}

}

2022-07-15 01:26 UTC, Insprill commented on src/test/java/be/seeseemelk/mockbukkit/inventory/BeaconInventoryMockTest.java
> +}
```suggestion
	}

}

2022-07-15 01:26 UTC, Insprill commented on src/test/java/be/seeseemelk/mockbukkit/inventory/BeaconInventoryMockTest.java
> +	BeaconInventoryMock inventory;
```suggestion
	private ServerMock server;
	private BeaconInventoryMock inventory;

2022-07-15 04:03 UTC, Insprill approved these changes
LGTM

2022-07-15 04:06 UTC, merged