Removed dead switch-cases (Uncreatable Inventories)
MockBukkit/MockBukkit pull request #554
Opened 2022-07-18 19:11 UTC by thelooter

# Description
Add Uncreatable Inventories

# Checklist
The following items should be checked before the pull request can be merged.
- [x] Unit tests added.
- [x] Code follows existing code format.

# Info on creating a pull request
- Make sure that unit tests are added which test the relevant changes.
- Make sure that the changes follow the existing code format.

# For maintainer
When a PR is approved, the maintainer should label this PR with `release/*`.

- If the PR fixes a bug in MockBukkit, update the patch version. (if the current version is `0.4.1`, the new version should be `0.4.2`)
- If the PR adds a new feature to MockBukkit, update minor version. (if the current version is `0.4.1`, the new version should be `0.5.0`)

Note that a PR that fixes an `UnimplementedOperationException` should be considered a new version and not a bugfix.

2022-07-18 21:20 UTC, Insprill requested changes
Perhaps InventoryType#isCreatable should be used before the switch?

2022-07-18 21:38 UTC, thelooter commented
> Perhaps InventoryType#isCreatable should be used before the switch?

What about filtering the InventoryType Enum to an EnumList that only contains the creatable Inventories and then create the switch from that.

2022-07-18 23:51 UTC, Insprill commented
Can you elaborate? I'm not totally sure what you mean since switch cases must be there at compile time

2022-07-19 16:46 UTC, Insprill requested changes

2022-07-19 16:46 UTC, Insprill commented on src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
> +			throw new UnsupportedOperationException("Merchant Inventory can't be created");
There is already an if statement guarding the switch so these cases can never be reached
```suggestion
```

2022-07-19 20:56 UTC, Insprill approved these changes
LGTM

2022-07-19 22:02 UTC, TheBusyBiscuit approved these changes

2022-07-19 22:03 UTC, merged