Fix publishing to maven local not working
MockBukkit/MockBukkit pull request #594
Opened 2022-08-02 00:24 UTC by Insprill

# Description
Fixes Gradle trying to sign jars locally by checking if the `CI` env var exists, rather than `JITPACK`. ([source](https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables))

This also makes it so the version is the git revision prefixed with `dev-` when built locally, since the `mockbukkit.version` property only exists when running in the GitHub action.

# Checklist
The following items should be checked before the pull request can be merged.
- [ ] Unit tests added.
- [x] Code follows existing code format.

# Info on creating a pull request
- Make sure that unit tests are added which test the relevant changes.
- Make sure that the changes follow the existing code format.

# For maintainer
When a PR is approved, the maintainer should label this PR with `release/*`.

- If the PR fixes a bug in MockBukkit, update the patch version. (if the current version is `0.4.1`, the new version should be `0.4.2`)
- If the PR adds a new feature to MockBukkit, update minor version. (if the current version is `0.4.1`, the new version should be `0.5.0`)

Note that a PR that fixes an `UnimplementedOperationException` should be considered a new version and not a bugfix.

2022-08-03 13:40 UTC, TheBusyBiscuit requested changes

2022-08-03 13:40 UTC, TheBusyBiscuit commented on build.gradle
> +    required { !isFork && System.getenv('CI') != null }
What about jitpack compatibility though?
This would break that, wouldn't it?

2022-08-03 20:52 UTC, Insprill commented on build.gradle
> +    required { !isFork && System.getenv('CI') != null }
It shouldn't, no. Before, it wouldn't sign if `JITPACK` was present. Now, it won't sign if `CI` *isn't* present, which anywhere outside of GitHub actions, its not.

2022-08-06 10:01 UTC, TheBusyBiscuit commented on build.gradle
> +    required { !isFork && System.getenv('CI') != null }
Alright

2022-08-06 10:01 UTC, TheBusyBiscuit approved these changes
lgtm

2022-08-06 10:08 UTC, merged