Add Egg Mock
MockBukkit/MockBukkit pull request #610
Opened 2022-08-11 18:16 UTC by thelooter

# Description
Add Egg Mock

# Checklist
The following items should be checked before the pull request can be merged.
- [x] Unit tests added.
- [x] Code follows existing code format.

# Info on creating a pull request
- Make sure that unit tests are added which test the relevant changes.
- Make sure that the changes follow the existing code format.

# For maintainer
When a PR is approved, the maintainer should label this PR with `release/*`.

- If the PR fixes a bug in MockBukkit, update the patch version. (if the current version is `0.4.1`, the new version should be `0.4.2`)
- If the PR adds a new feature to MockBukkit, update minor version. (if the current version is `0.4.1`, the new version should be `0.5.0`)

Note that a PR that fixes an `UnimplementedOperationException` should be considered a new version and not a bugfix.

2022-08-11 22:52 UTC, Insprill requested changes

2022-08-11 22:52 UTC, Insprill commented on src/main/java/be/seeseemelk/mockbukkit/entity/ThrowableProjectileMock.java
> +	public abstract void setItem(@NotNull ItemStack item);
Are these necessary? If removed inheriting classes will still have to override them.

And if the implementation is the same for everything that inherits, can't they be implemented here?

2022-08-13 00:17 UTC, Insprill approved these changes
LGTM

2022-08-13 00:17 UTC, merged

2023-10-09 20:00 UTC, Farlimb commented
Can i work on this issue?