Add Pig Mock
MockBukkit/MockBukkit pull request #611
Opened 2022-08-11 20:10 UTC by thelooter

# Description
State the changes of the pull request here.

# Checklist
The following items should be checked before the pull request can be merged.
- [x] Unit tests added.
- [x] Code follows existing code format.

# Info on creating a pull request
- Make sure that unit tests are added which test the relevant changes.
- Make sure that the changes follow the existing code format.

# For maintainer
When a PR is approved, the maintainer should label this PR with `release/*`.

- If the PR fixes a bug in MockBukkit, update the patch version. (if the current version is `0.4.1`, the new version should be `0.4.2`)
- If the PR adds a new feature to MockBukkit, update minor version. (if the current version is `0.4.1`, the new version should be `0.5.0`)

Note that a PR that fixes an `UnimplementedOperationException` should be considered a new version and not a bugfix.

2022-08-11 23:04 UTC, Insprill requested changes

2022-08-11 23:04 UTC, Insprill commented on src/main/java/be/seeseemelk/mockbukkit/entity/PigMock.java
> +			return;
Should this throw an exception instead of returning?

2022-08-12 22:33 UTC, Insprill requested changes

2022-08-12 22:33 UTC, Insprill commented on src/main/java/be/seeseemelk/mockbukkit/entity/PigMock.java
> +		Preconditions.checkArgument(ticks >= 0 && ticks <= this.boostTicks, "boost ticks must not exceed 0 or %d (inclusive)", this.boostTicks);
```suggestion
		Preconditions.checkArgument(ticks >= 0 && ticks <= this.boostTicks, "Current Boost Ticks must be less than Boost Ticks (#getBoostTicks)");

2022-08-12 22:44 UTC, thelooter commented on src/main/java/be/seeseemelk/mockbukkit/entity/PigMock.java
> +			return;
Closed since we should replicate Bukkit Behaviour (Reference Discord for Discussion)

2022-08-12 23:57 UTC, Insprill approved these changes
LGTM

2022-08-12 23:57 UTC, merged