Pretend swing packet gets sent
MockBukkit/MockBukkit pull request #635
Opened 2022-09-11 01:01 UTC by SplotyCode

# Description
Pretend swing packet gets sent

# Checklist
The following items should be checked before the pull request can be merged.
- [X] Unit tests added.
- [X] Code follows existing code format.

# Info on creating a pull request
- Make sure that unit tests are added which test the relevant changes.
- Make sure that the changes follow the existing code format.

# For maintainer
When a PR is approved, the maintainer should label this PR with `release/*`.

- If the PR fixes a bug in MockBukkit, update the patch version. (if the current version is `0.4.1`, the new version should be `0.4.2`)
- If the PR adds a new feature to MockBukkit, update minor version. (if the current version is `0.4.1`, the new version should be `0.5.0`)

Note that a PR that fixes an `UnimplementedOperationException` should be considered a new version and not a bugfix.

2022-09-11 01:04 UTC, SplotyCode commented
Seemed to be fixed with https://github.com/MockBukkit/MockBukkit/pull/632 3 hours ago. Will leave this open if you want to merge the unit tests

2022-09-11 01:39 UTC, Insprill requested changes

2022-09-11 01:39 UTC, Insprill commented on src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
> +
Since this functionality is now handled by LivingEntityMock, it should be moved to that test class.

2022-09-12 00:50 UTC, Insprill requested changes

2022-09-12 00:50 UTC, Insprill commented on src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java
> +
```suggestion

2022-09-12 00:51 UTC, Insprill approved these changes
LGTM

2022-09-12 01:14 UTC, merged