Implement scoreboard criteria
MockBukkit/MockBukkit pull request #654
Opened 2022-10-05 18:14 UTC by syldium

# Description
Scoreboard objectives now use the [new `Criteria` interface](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/d43a1e722f50396694cfaaa96f6059ca533d7b45). This PR also implements entity related methods on scoreboards and objective and fixes a nullability issue with `Objective#displayName()`.

# Checklist
The following items should be checked before the pull request can be merged.
- [x] Unit tests added.
- [x] Code follows existing code format.

# Info on creating a pull request
- Make sure that unit tests are added which test the relevant changes.
- Make sure that the changes follow the existing code format.

# For maintainer
When a PR is approved, the maintainer should label this PR with `release/*`.

- If the PR fixes a bug in MockBukkit, update the patch version. (if the current version is `0.4.1`, the new version should be `0.4.2`)
- If the PR adds a new feature to MockBukkit, update minor version. (if the current version is `0.4.1`, the new version should be `0.5.0`)

Note that a PR that fixes an `UnimplementedOperationException` should be considered a new version and not a bugfix.

2022-10-06 22:09 UTC, thelooter requested changes
Some small Stuff

2022-10-06 22:09 UTC, thelooter commented on src/main/java/be/seeseemelk/mockbukkit/ServerMock.java
> +		return this.criteria.computeIfAbsent(name, CriteriaMock::new);
Please add a null Check

2022-10-06 22:09 UTC, thelooter commented on src/main/java/be/seeseemelk/mockbukkit/scoreboard/CriteriaMock.java
> +	public CriteriaMock(String name)
```suggestion
	public CriteriaMock(@NotNull String name)
```

2022-10-06 22:09 UTC, thelooter commented on src/main/java/be/seeseemelk/mockbukkit/scoreboard/ScoreboardMock.java
> +		if (this.objectives.containsKey(name))
Please add Null Checks for the Paramenters

2022-10-06 22:09 UTC, thelooter commented on src/main/java/be/seeseemelk/mockbukkit/scoreboard/ScoreboardMock.java
> +		return objectives.values().stream().filter(objective -> objective.getTrackedCriteria().equals(criteria))
Please add a Null Check

2022-10-07 20:02 UTC, Insprill requested changes

2022-10-07 20:02 UTC, Insprill commented on src/main/java/be/seeseemelk/mockbukkit/scoreboard/CriteriaMock.java
> +	private final String name;
```suggestion
{

	private final String name;

2022-10-07 20:02 UTC, Insprill commented on src/main/java/be/seeseemelk/mockbukkit/scoreboard/CriteriaMock.java
> +	{
Missing null check

2022-10-07 20:02 UTC, Insprill commented on src/main/java/be/seeseemelk/mockbukkit/scoreboard/ScoreboardMock.java
>  {
```suggestion
{

```

2022-10-07 20:02 UTC, Insprill commented on src/main/java/be/seeseemelk/mockbukkit/scoreboard/ScoreboardMock.java
> +
```suggestion

2022-10-07 20:02 UTC, Insprill commented on src/main/java/be/seeseemelk/mockbukkit/scoreboard/ScoreboardMock.java
> +		}
```suggestion
		Preconditions.checkArgument(!this.objectives.containsKey(name), "An objective of name '" + name + "' already exists");

2022-10-07 20:02 UTC, Insprill commented on src/main/java/be/seeseemelk/mockbukkit/scoreboard/ScoreboardMock.java
> +				.collect(Collectors.toSet());
```suggestion
		return objectives.values().stream()
				.filter(objective -> objective.getTrackedCriteria().equals(criteria))
				.collect(Collectors.toSet());
```

2022-10-07 20:09 UTC, Insprill approved these changes
LGTM. Thank you!

2022-10-07 20:46 UTC, thelooter approved these changes

2022-10-07 20:47 UTC, merged