Add Adventure BossBar viewing
MockBukkit/MockBukkit pull request #795
Opened 2023-06-26 06:37 UTC by gabber235

# Description
Added a list for the currently viewed Adventure BossBars for entities. This allows you to test what Adventure BossBars an entity sees.

# Checklist
The following items should be checked before the pull request can be merged.
- [x] Code follows existing style.
- [x] Unit tests added (if applicable).

2023-06-27 15:53 UTC, thelooter requested changes
Just some small things

2023-06-27 15:53 UTC, thelooter commented on src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
> +		this.bossBars.add(bar);
```suggestion
        Preconditions.checkNotNull(bar, "Bossbar cannot be null");
		this.bossBars.add(bar);
```

2023-06-27 15:53 UTC, thelooter commented on src/main/java/be/seeseemelk/mockbukkit/entity/EntityMock.java
> +		this.bossBars.remove(bar);
```suggestion
        Preconditions.checkNotNull(bar, "Bossbar cannot be null");
		this.bossBars.remove(bar);
```

2023-06-27 17:48 UTC, thelooter commented
Can you please rebase this into v1.20

2023-06-30 13:15 UTC, gabber235 commented
> Can you please rebase this into v1.20

You mean changing the base branch to the v1.20? When I do that it gives a merge conflict on a file I didn't touch. 
What would you want me to do exactly?

2023-06-30 17:51 UTC, Insprill commented
I'd checkout the 1.20 branch, cherrypick your commit onto it, then force push and change the base branch

2023-07-01 17:20 UTC, gabber235 commented
I can't change the branch for the pull request. I made a new pull-request for the 1.20 version #806

2023-07-01 17:20 UTC, closed without merging