BukkitSchedulerMock.java add missing methods
MockBukkit/MockBukkit pull request #797
Opened 2023-06-27 22:35 UTC by NeumimTo

# Description
Implements isCurrentlyRunning and runTaskAsynchronously

# Checklist
The following items should be checked before the pull request can be merged.
- [ x] Code follows existing style.
- [ x] Unit tests added (if applicable).

2023-06-27 22:43 UTC, NeumimTo commented
Locally all tests pass, so im just going to blame your ci, since i did not even touch code relevant to that failing test.

2023-06-29 15:34 UTC, thelooter requested changes
One small change

2023-06-29 15:34 UTC, thelooter commented on src/main/java/be/seeseemelk/mockbukkit/scheduler/BukkitSchedulerMock.java
> +		ScheduledTask scheduledTask = new ScheduledTask(id.getAndIncrement(), plugin, false, currentTick, task);
```suggestion
		ScheduledTask scheduledTask = new ScheduledTask(this.id.getAndIncrement(), plugin, false, this.currentTick, task);
```

2023-06-29 15:40 UTC, thelooter approved these changes

2023-06-29 15:41 UTC, thelooter commented
Not gonna merge just yet, since our CI isn't working rn. Will merge once that is fixed

2023-07-08 17:15 UTC, merged