Add Adventure docs
MockBukkit/MockBukkit pull request #798
Opened 2023-06-28 14:57 UTC by mattboy9921

# Description
Adds a page to the docs for Adventure specific information

# Checklist
The following items should be checked before the pull request can be merged.
- [x] Code follows existing style.
- [ ] Unit tests added (if applicable).

2023-06-29 18:54 UTC, syldium requested changes

2023-06-29 18:54 UTC, syldium commented on docs/adventure.rst
> +When using MockBukkit with `Adventure <https://github.com/KyoriPowered/adventure>`_,
```suggestion
When using MockBukkit with `the non-native implementation of Adventure <https://github.com/KyoriPowered/adventure-platform>`_, 
```

2023-06-29 18:54 UTC, syldium commented on docs/adventure.rst
> +=========
```suggestion
Adventure
=========

Platform
--------
```
Adventure is also natively implemented in Paper.

2023-07-08 19:19 UTC, thelooter approved these changes

2023-07-08 19:19 UTC, merged