Add main Contributors to POM
MockBukkit/MockBukkit pull request #821
Opened 2023-07-15 11:47 UTC by thelooter

# Description
Adds the main Contributors to the pom

# Checklist
The following items should be checked before the pull request can be merged.
- [x] Code follows existing style.
- [ ] Unit tests added (if applicable).

2023-07-15 19:39 UTC, Insprill requested changes

2023-07-15 19:39 UTC, Insprill commented on build.gradle.kts
> +						id.set("TheBusyBiscuit")
Shouldn't his ID be lowercase like the rest?

2023-07-16 20:45 UTC, TheBusyBiscuit commented on build.gradle.kts
> +						email.set("mrCookieSlime@gmail.com")
Please don't just put my email there...
If anything use the public one that's linked everywhere... `slimefuncontact@gmail.com`.
But I much prefer not having any email set for me.

2023-07-16 22:25 UTC, Insprill approved these changes
LGTM

2023-07-22 11:05 UTC, merged