Implement getNearbyEntities
MockBukkit/MockBukkit pull request #824
Opened 2023-07-18 21:34 UTC by nothub

# Description
This PR implements `getNearbyEntities` in 4 variations.

# Checklist
The following items should be checked before the pull request can be merged.
- [x] Code follows existing style.
- [ ] ~~Unit tests added (if applicable).~~

2023-07-18 22:02 UTC, Insprill requested changes
Looks good, but please add unit tests.

2023-07-19 08:18 UTC, nothub commented
I added 2 Tests, one for testing the distance filter and one for testing the predicate filter.

2023-07-19 11:24 UTC, thelooter requested changes

2023-07-19 11:24 UTC, thelooter commented on src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
>  	}
Please add a Test for this

2023-07-19 15:19 UTC, nothub commented on src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
>  	}
Tests added for BoundingBox methods.

2023-07-19 16:59 UTC, thelooter reviewed
LGTM

2023-07-19 17:00 UTC, thelooter approved these changes

2023-07-19 18:07 UTC, Insprill approved these changes
LGTM. Thank you!

2023-07-19 18:07 UTC, merged