Implement most methods related to getHighestBlock(Y)At
MockBukkit/MockBukkit pull request #857
Opened 2023-09-20 12:21 UTC by Thorinwasher

# Description
Implement the following methods in WorldMock:
- getHighestBlockYAt(int,int)
- getHighestBlockYat(Location)
- getHighestBlockAt(int,int)
- getHighestBlockAt(Location)
- getHighestBlockYAt(int,int,HeightMap)
- getHighestBlockYAt(Location,HeightMap)
- getHighestBlockAt(int,int,HeightMap)
- getHighestBlockAt(Location,HeightMap

BlockMock#isSolid() is not implemented yet, that makes 4 of these tests to skip.

# Checklist
The following items should be checked before the pull request can be merged.
- [ ] Code follows existing style.
- [ ] Unit tests added (if applicable).

2023-09-20 15:54 UTC, thelooter commented
I don't think it makes sense to merge this until `BlockMock#isSolid()` is implemented

2023-10-23 16:17 UTC, Insprill requested changes, later dismissed

2023-10-23 16:17 UTC, Insprill commented on src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
> +import org.bukkit.*;
No wildcard imports.

2023-10-23 16:17 UTC, Insprill commented on src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
> +				boolean isWaterLogged = false;
```suggestion
boolean isWaterLogged = block.getBlockData() instanceof Waterlogged waterlogged && waterlogged.isWaterlogged();

2023-10-23 16:17 UTC, Insprill commented on src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
> +			case OCEAN_FLOOR_WG, WORLD_SURFACE_WG -> throw new UnimplementedOperationException();
What's the condition for these? Can we implement them?

2023-10-27 16:55 UTC, Thorinwasher commented on src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
> +import org.bukkit.*;
Alright, that's my auto formatting. Let me see if I can fix that. I dislike them as well

2023-10-27 17:00 UTC, Thorinwasher commented on src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
> +			case OCEAN_FLOOR_WG, WORLD_SURFACE_WG -> throw new UnimplementedOperationException();
WG, I think that stands for world generation. So this has to relate to how the world was generated. Should be doable as the worlds are quite simple (just flat worlds)

2023-10-28 12:46 UTC, thelooter commented on src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
> +import org.bukkit.*;
Go to IntelliJ Settings > Editor > Code Style > Java > Imports and set both
- Class count to use import with .*
- Names count to use import with .*

to an insanely high number like 99999999

2023-11-26 17:28 UTC, thelooter approved these changes
LGTM

2023-11-26 17:28 UTC, merged