implements the Panda entity
MockBukkit/MockBukkit pull request #859
Opened 2023-09-21 12:54 UTC by Nirbose

# Description
Adding the PandeMock class
Adding the PandeMockTest class
Added support for Panda entity in WorldMock *mockEntity(...)*

# Checklist
The following items should be checked before the pull request can be merged.
- [x] Code follows existing style.
- [x] Unit tests added (if applicable).

2023-09-21 18:31 UTC, thelooter requested changes

2023-09-21 18:31 UTC, thelooter commented on src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
> +		}
There should be a Test added to the Parameterized Test for this in WorldMockTest

2023-09-21 19:29 UTC, Nirbose commented on src/main/java/be/seeseemelk/mockbukkit/WorldMock.java
> +		}
Add to commit 0068a68b0554835bbd19d971ac3d62fdb6b4ac69

2023-09-30 20:30 UTC, thelooter approved these changes

2023-09-30 20:30 UTC, merged