Implemented block light, light from sky and light from blocks at Bloc…
MockBukkit/MockBukkit pull request #970
Opened 2024-02-16 00:39 UTC by 4everTheOne

# Description
Implement getters and setters for BlockMock to resolve issue https://github.com/MockBukkit/MockBukkit/issues/953.

I did not include any hard restriction on the values, so end-users can decide what values suites well. But this includes a soft-warning with the annotation `@Range(from=0, to=15)` to notify the user's that they providing values outside of default Paper values.

See: https://jd.papermc.io/paper/1.20/org/bukkit/block/Block.html#getLightLevel()

# Checklist
The following items should be checked before the pull request can be merged.
- [X] Code follows existing style.
- [X] Unit tests added (if applicable).

2024-02-16 10:25 UTC, Thorinwasher requested changes

2024-02-16 10:25 UTC, Thorinwasher commented on src/main/java/be/seeseemelk/mockbukkit/block/BlockMock.java
> +		return lightLevel;
Looked into the source code of paper, this value is the max value of `lightFromSky` and `lightFromBlocks`. Not it's own field

2024-02-16 10:25 UTC, Thorinwasher commented on src/main/java/be/seeseemelk/mockbukkit/block/BlockMock.java
> +		this.lightFromSky = lightFromSky;
Be more stringent with the input; have a precondition check for this and `setLightFromBlocks`

2024-02-16 19:10 UTC, 4everTheOne commented
Thank you for the feedback! I have updated the code according to the suggested changes.

2024-02-17 08:17 UTC, Thorinwasher commented on src/main/java/be/seeseemelk/mockbukkit/block/BlockMock.java
> +		if (lightFromSky < 0 || lightFromSky > 15) {
Use Preconditions.checkArgument(boolean, String) instead

2024-02-17 17:15 UTC, Thorinwasher approved these changes

2024-02-17 17:15 UTC, merged