Add `Maker` mock
MockBukkit/MockBukkit pull request #976
Opened 2024-02-23 18:10 UTC by Seggan

# Description

Added `MarkerMock` and added it to `WorldMock`. No separate unit test because it has no separate behavior from `EntityMock`.

# Checklist
The following items should be checked before the pull request can be merged.
- [x] Code follows existing style.
- [x] Unit tests added (if applicable).

2024-02-23 18:13 UTC, Seggan commented
I don't see error?

2024-02-23 18:15 UTC, Seggan commented
Ah, `error: SignMock is not abstract and does not override abstract method getAllowedEditor() in Sign`. Should I implement this? Not really within the PR scope

2024-02-23 19:10 UTC, Thorinwasher commented
> Ah, error: SignMock is not abstract and does not override abstract method getAllowedEditor() in Sign. Should I implement this? Not really within the PR scope

That should be in a separate PR

2024-02-24 14:27 UTC, Thorinwasher requested changes
Although Marker does not have a different interface than Entity, the behavior is a bit different. Here's the difference:

It's not possible for it to have any passengers; the Marker#addPassenger(Entity) method should not add any passengers to it and always return false.

(There's one more difference, but that is not implemented in EntityMock anyhow)

2024-02-24 20:27 UTC, Thorinwasher requested changes
I forgot to mention that there's a test in WorldMockTest which checks all spawnable entities (check for a huge Stream of EntityTypes and entity classes). Please add MarkerMock to that test.

2024-02-26 03:42 UTC, Seggan commented on src/test/java/be/seeseemelk/mockbukkit/WorldMockTest.java
> +				Arguments.of(EntityType.MARKER, MarkerMock.class)
@Thorinwasher already done

2024-02-27 08:15 UTC, Thorinwasher approved these changes
Looks good to me!

I missed that you already added the test there, sorry about that.

2024-02-27 08:15 UTC, merged